config/routes.rb
Rails.application.routes.draw do
   
    root 'users#new'
  
    resources :categories do 
      resources :recipes
    end
    
    resources :users do 
      resources :recipes
      end
  
    resources :recipes do
      resources :ingredients
    end 
    

    resources :ingredients
  
    get    '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users

    get '/auth/facebook/callback' => 'sessions#createfb'
    
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :recipes
    has_many :users, through: :recipes

    validates :name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    belongs_to :recipe

    validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    scope :by_date, -> {order(created_at: 'asc') }
    scope :by_category, ->(name) { joins(:category).where(categories: {name: name.titleize})}
    has_many :ingredients
    belongs_to :category
    belongs_to :user
    validates :name, presence: true


    # def self.by_category(name)
    #     joins(:category).where(categories: { name: name.titleize})
    # end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :recipes
  has_many :categories, through: :recipes
  has_many :ingredients, through: :recipes
    
  validates :name, presence: true, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
 
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    def index
        @categories = Category.all
    end 
    
    def show 
        @category = Category.find_by(id: params[:id])
    end 

    def new 
        @category = Category.new
    end 

    def create 
        @category = Category.find_or_create_by(name: params[:category][:name].titleize)
        if @category.save
            redirect_to new_category_recipe_path(@category)
        else
            
            render :new
        end 
    end 

    def update
        @category = Category.find_or_create_by(category_params)
        if @category.save
            redirect_to new_category_recipe_path(@category)
        else
            
            render :new
        end 
    end 

    private 

    def category_params
        params.require(:category).permit(:name)
    end 
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    def index
        @ingredients = Ingredient.where("recipe_id": params[:recipe_id]).all
    end 

    def show
        @ingredient = Ingredient.find(params[:id])
    end 

    def new
        recipe = Recipe.find(params[:recipe_id])
        @ingredient = recipe.ingredients.build
    end 

    def create
        
        @ingredient = Ingredient.find_or_create_by(ingredient_params)
        if @ingredient.save
         redirect_to recipe_path(@ingredient.recipe_id)
        else
            render :new
        end
    end 
    
    private

    def ingredient_params
            params.require(:ingredient).permit(:name, :recipe_id)
    end 

    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index 
        # @recipes = Recipe.where("user_id": params[:user_id]).all
        if params[:filter]
            @recipes = Recipe.by_date.by_category(params[:filter])
        else
            @recipes = Recipe.all
        end
    
    end 

    def show
        @recipe = Recipe.find(params[:id])
    end 

    def new
        @user = User.find(current_user.id)
        @recipe = @user.recipes.build
        @category = params[:category_id]
        @recipe.category_id = @category
    end

    def create
         if current_user.id == recipe_params[:user_id].to_i
            @recipe = Recipe.new(recipe_params)
            if @recipe.save
                redirect_to @recipe
            else
                render :new
            end
         end
    end 
    
    private

    def recipe_params
            params.require(:recipe).permit(:name, :user_id, :category_id)
    end 

end


   

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(name: params[:session][:name].downcase)
    if @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else 
      
    render 'new'
    end
  end 
  
  
  def createfb
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
      u.password = SecureRandom.hex(12)
    end
    session[:user_id] = @user.id

    redirect_to @user
  end

  def destroy
    session.clear
    redirect_to root_url
  end

  

  private
 
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def index 
       @users = User.all
  end 

  def show
     @user = User.find(params[:id])
     @recipes = Recipe.find_by(user_id: params[:id]) 
  end 

  def new
      
     @user = User.new
       
  end 

  def create
      @user = User.new(user_params)
      if @user.save
          log_in @user
       redirect_to user_path(@user)
      else 
       render :new 
      end
  end 

  private

  def user_params
          params.require(:user).permit(:name, :password)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
      end
      
      def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
      end
      
      def logged_in?
        !current_user.nil?
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>Here are all the Categories created by users</h1>
    <% @categories.each do |t|%>
        <ul><%= link_to t.name, category_path(t.id) %></ul>
    <%end%>

app/views/categories/new.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@category.errors.count, "error") %>
      prohibited this error from being saved:
    </h2>
 
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>


<%= form_for @category do |f| %>
    <label>Category name:</label>
    <%= f.text_field :name %>
    <%= f.submit "Create"%>
<%end%>

app/views/categories/show.html.erb
<h1>Here are all the recipes users have created for the <%= @category.name %> category</h1>
    <% @category.recipes.each do |t|%>
        <ul>
            <h3><%= link_to t.name, recipe_path(t.id) %></h3>
        </ul>
    <%end%>

app/views/ingredients/index.html.erb
<h1><% @ingredients.each do |t|%>
    <%= t.name %>
<%end%></h1>

app/views/ingredients/new.html.erb
<% if @ingredient.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@ingredient.errors.count, "error") %>
      prohibited this error from being saved:
    </h2>
 
    <ul>
    <% @ingredient.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @ingredient do |f| %>
    <label>Ingredient name:</label>
    <%= f.hidden_field :recipe_id %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>

app/views/ingredients/show.html.erb
This is the <%= @ingredient.name %> Show page

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html> 
  <head>
    <title>RecipeManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <% if logged_in? %>
    <%= link_to "Log out", logout_path, method: :delete %>
      <h1><%= link_to current_user.name, user_path(current_user.id) %></h1>
   <%end%>

    <h2><%= link_to "Categories", categories_path %></h2>
    <h2><%= link_to "Recipes", recipes_path %></h2>
   
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Here are all the recipes that users have created</h1>
    <% @recipes.each do |t|%>
        <ul><%=link_to t.name, recipe_path(t.id) %></ul>
    <%end%>

    <%= form_tag(recipes_path, method: :get) do %>
        <%= text_field_tag :filter, params[:filter] %>
        <%= submit_tag "filter"%>
        <%end %>

app/views/recipes/new.html.erb
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
      prohibited this error from being saved:
    </h2>
 
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<%= form_for @recipe do |f| %>
    <label>Recipe name:</label>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :category_id %>
    <%= f.text_field :name %>
    <%= f.submit %>
<%end%>

app/views/recipes/show.html.erb
<h2><%= @recipe.category.name %></h2>
<h3><%= @recipe.name %></h3>
<% @recipe.ingredients.each do |t| %>
    <li><%= t.name %></li>
    <%end%>
<%= link_to "Add Ingredient", new_recipe_ingredient_path(@recipe) %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :uid %>
    <%= form.text_field :uid %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Image</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.image %></td>
        <td><%= user.uid %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this error from being saved:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Welcome To The Recipes Manager Site</h1>
<h2>You can create your own recipes and view recipes created by other users</h2>
<h3>Sign Up</h3>


<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Submit" %>
<% end %>


<h4>OR </h4>


<%= link_to "Log In", login_path %>

<h4>OR </h4>

  <%= link_to('Log in with Facebook!', '/auth/facebook') %>

app/views/users/show.html.erb
<h2>Here are the recipes you have created</h2>
<% @user.recipes.each do |t|%>
  <h4><%= link_to t.name, user_recipe_path(@user, t.id) %></h4>
<div>

<%end%>
<%= link_to "Please Choose A Category For Your New Recipe", new_category_path %>